rootProject.name = "runescape-emulator"
include("rse-engine")
include("rse-utilities")
include("rse-cache")
include("rse-application")
include("rse-entity")
include("rse-world")
include("rse-network")
include("rse-buffer")
include("rse-service")
include("rse-cache:definition")
include("rse-api", "rse-api:entity", "rse-api:region", "rse-api:collections", "rse-api:definitions")
include("rse-network-js5")
include("rse-network-world")
include("rse-encryption")
include("rse-database")
