rootProject.name = "runescape-emulator"
include("rse-engine")
include("rse-utilities")
include("rse-cache")
include("rse-application")
include("rse-gson")
include(
    "rse-entity",
    "rse-entity:actor",
    "rse-entity:player",
    "rse-entity:npc",
    "rse-entity:update",
    "rse-entity:details"
)
include("rse-entity", "rse-entity:actor", "rse-entity:player", "rse-entity:npc", "rse-entity:update", "rse-entity:widget")
include("rse-world")
include("rse-network")
include("rse-buffer")
include("rse-service")
include("rse-cache:definition")
include(
    "rse-api",
    "rse-api:entity",
    "rse-api:region",
    "rse-api:collections",
    "rse-api:definitions",
    "rse-api:core",
    "rse-api:widgets",
    "rse-api:skills",
    "rse-api:reactive",
    "rse-api:region-zones",
    "rse-api:persistent-details"
)
include(
    "rse-plugins",
    "rse-plugins:commands",
    "rse-plugins:system",
    "rse-plugins:report-abuse"
)
include("rse-network-js5")
include("rse-network-world")
include("rse-encryption")
include("rse-database")
include("rse-service-login")
include("rse-network-packet")
include("rse-messages")
include("rse-packet", "rse-packet:message", "rse-packet:encoders", "rse-packet:decoders", "rse-packet:packet-api")
include("rse-map")
include("rse-world-repository")
include("rse-map:route")
