rootProject.name = "runescape-emulator"
include("rse-engine")
include("rse-utilities")
include("rse-cache")
include("rse-application")
include("rse-entity")
include("rse-world")
include("rse-network")
include("rse-buffer")
include("rse-service")
