package rs.emulator.map.collision

/**
 *
 * @author Chk
 */
enum class CollisionFlags(val flag: Int)
{

    NORTH_WALL(0X2),

    NORTH_WALL_BLOCK_PROJECTILE(0X400),

    NORTH_WALL_BLOCK_INTERACTION(0X800000),

    NORTH_WEST_PARTIAL(0X1),

    NORTH_WEST_PARTIAL_BLOCK_PROJECTILE(0X200),

    NORTH_WEST_PARTIAL_BLOCK_INTERACTION(0X400000),

    NORTH_EAST_PARTIAL(0X4),

    NORTH_EAST_PARTIAL_BLOCK_PROJECTILE(0X800),

    NORTH_EAST_PARTIAL_BLOCK_INTERACTION(0X1000000),

    EAST_WALL(0X8),

    EAST_WALL_BLOCK_PROJECTILE(0X1000),

    EAST_WALL_BLOCK_INTERACTION(0X2000000),

    SOUTH_EAST_PARTIAL(0X10),

    SOUTH_EAST_PARTIAL_BLOCK_PROJECTILE(0X2000),

    SOUTH_EAST_PARTIAL_BLOCK_INTERACTION(0X4000000),

    SOUTH_WALL(0X20),

    SOUTH_WALL_BLOCK_PROJECTILE(0X4000),

    SOUTH_WALL_BLOCK_INTERACTION(0X8000000),

    SOUTH_WEST_PARTIAL(0X40),

    SOUTH_WEST_PARTIAL_BLOCK_PROJECTILE(0X8000),

    SOUTH_WEST_PARTIAL_BLOCK_INTERACTION(0X10000000),

    WEST_WALL(0X80),

    WEST_WALL_BLOCK_PROJECTILE(0X10000),

    WEST_WALL_BLOCK_INTERACTION(0X20000000),

    BLOCKING_OBJECT(0X100),

    BLOCKING_OBJECT_BLOCK_PROJECTILE(0X20000),

    BLOCKING_OBJECT_BLOCK_INTERACTION(0X40000000),

    BLOCKING_FLOOR_DECORATION(0X40000),

    SIDE_ONLY_INTERACTION(0X80000),

    BLOCK_TILE_WALK(0X200000),

    BLOCK_TILE_COMPLETE(BLOCK_TILE_WALK.flag or BLOCKING_FLOOR_DECORATION.flag or BLOCKING_OBJECT.flag),

    BLOCK_TILE_NORTH_WEST(SOUTH_EAST_PARTIAL.flag or SOUTH_WALL.flag or BLOCK_TILE_COMPLETE.flag or EAST_WALL.flag),

    BLOCK_TILE_NORTH(SOUTH_WALL.flag or BLOCK_TILE_COMPLETE.flag),

    BLOCK_TILE_NORTH_EAST(SOUTH_WEST_PARTIAL.flag or SOUTH_WALL.flag or WEST_WALL.flag or BLOCK_TILE_COMPLETE.flag),

    BLOCK_TILE_EAST(WEST_WALL.flag or BLOCK_TILE_COMPLETE.flag),

    BLOCK_TILE_SOUTH_EAST(NORTH_WEST_PARTIAL.flag or NORTH_WALL.flag or WEST_WALL.flag or BLOCK_TILE_COMPLETE.flag),

    BLOCK_TILE_SOUTH(NORTH_WALL.flag or BLOCK_TILE_COMPLETE.flag),

    BLOCK_TILE_SOUTH_WEST(NORTH_EAST_PARTIAL.flag or NORTH_WALL.flag or EAST_WALL.flag or BLOCK_TILE_COMPLETE.flag),

    BLOCK_TILE_WEST(EAST_WALL.flag or BLOCK_TILE_COMPLETE.flag),

    //Todo: BLOCK_PROJECTILE_COMPLETE(BLOCK)

    ;

}